services:
  udpredirect:
    privileged: true
    init: true
    image: udpredirect:latest

  udpproducer:
    image: udpproducer:latest
    volumes:
      - /etc/localtime:/etc/localtime
    links:
        - udpredirect

